### ISSUE TITLE
GetAtt doesn't support multi-level Resource outputs 

### ISSUE THREAD

**Issue by chriswgerber** [cloudtools/troposphere#1042]
https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L410

You can view the list of attributes here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html#intrinsic-function-reference-getatt-attrib

In particular, Redshift Endpoints are in the form of "ResourceId.Endpoint.Address". The TemplateGenerator chocks trying to read a file that references that Endpoint. It looks like it attempts to break up the string into multiple elements to create the instance `GetAtt [ResourceId, Endpoint, Address]` rather than `GetAtt [ResourceId, Endpoint.Address]`.

**Comment by phobologic** [comment]
Thanks for the issue, @ThatGerber - can you please provide some example code, along with the error you're getting when trying to use it?  Thanks again!

**Comment by ThatGerber** [comment]
I forced some pip upgrades and it looks like it may have been fixed? My PoC isn't showing the error and I tested it with a couple of stacks that also weren't showing an error. It did reveal another bug, though, so I'll open a new ticket for that one. 

I'll check a few more stacks to see if can recreate today, otherwise I'll close this ticket. Thanks!

**Comment by phobologic** [comment]
Thanks @ThatGerber - let us know if you find anything, or if we can close. :)
