### ISSUE TITLE
tests fail on Python 3 because of 'basestring'

### ISSUE THREAD

**Issue by ror6ax** [cloudtools/troposphere#1091]
Running test suite on Python 3.6 leads to 

```
======================================================================
ERROR: test_CustomResource (tests.test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ror6ax/troposphere/.eggs/awacs-0.7.2-py3.6.egg/tests/test_examples.py", line 21, in test_file
    exec(code)
  File "examples/CustomResource.py", line 6, in <module>
    class CustomPlacementGroup(AWSCustomObject):
  File "examples/CustomResource.py", line 10, in CustomPlacementGroup
    'ServiceToken': (basestring, True),
NameError: name 'basestring' is not defined
```

**Comment by DrLuke** [comment]
That's because you have to manually convert it to python3 code before running the test. The Makefile isn't complete in that regard.

**Comment by cwgem** [comment]
I hate to dig up a rather well age thread, but Python 2.7 is EOL in January of 2020, giving a year before it's no longer officially supported. There doesn't seem to be any reasonable need to keep things at python 2 any longer. Instead of using a script to generate a python 3 version it feels like master should be converted to python 3 and continue from there.
