### ISSUE TITLE
troposphere is hard to install with Python 3

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#1299]
@cwgem I didn't want to subvert your Python 3 thread #1295 with this question so I'm opening up a new issue.

You commented:
```...Troposphere isn't Python 3 out of the box (the conversion script, while exists, can slightly complicate the process of deploying troposphere``` 

I know developing troposphere changes using Python 3 is difficult and I use Python 2 exclusively to maintain compatibility. But for installation, both a ```pip3 install``` and ```git clone/python setup.py install``` are pretty straightforward for installation. Could you elaborate on the installation or deployment issues in case I could alleviate it in the short term?

**Comment by cwgem** [comment]
Does the `pip3 install` give a python 3 supported install? From what I can tell the framework runs 2to3.py on the related code. While from what I understand this should give reasonable python 3 supported build, it's hard to tell whether or not this will occur with every release. Staying as close to original code is preferred for reducing volatility of the generated package.

With the git install method this assumes current master code is working okay. I've seen enough issues where our template deployment fails due to a bug ( see #1195 as an example ) so working off of master and doing the python install that way is not something I'd prefer from a reliability standpoint. While I could tag off release this requires me updating something whenever there is a new release which I'd like to avoid and be able to pick up the latest through a simple pip install.

**Comment by markpeek** [comment]
Currently the Travis test pipeline runs against Python versions 2.7, 3.4, 3.5, 3.6 (doh! need to add 3.7) so there is reasonable confidence that the code will work on Python3. I definitely do not plan to deprecate Python3 usage. :-) And I try to ensure the code on master will always show green build passing.

Both of these methods should work to easily install python3 either from PyPI or git:
```
# Install via PyPI
$ python3 -m venv tropo3
$ source tropo3/bin/activate
(tropo3) $ pip3 install troposphere
(tropo3) $ python3
Python 3.7.0 (default, Nov  7 2018, 14:45:25)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from troposphere import Template

# cleanup
(tropo3) $ deactivate
$ rm -rf tropo3

# Install from github - 2to3 will be run automatically
$ python3 -m venv tropo3
$ source tropo3/bin/activate
(tropo3) $ git clone git@github.com:cloudtools/troposphere.git
(tropo3) $ cd troposphere
(tropo3) $ python3 setup.py install
(tropo3) $ cd ..
(tropo3) $ python3
Python 3.7.0 (default, Nov  7 2018, 14:45:25)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from troposphere import Template
```

**Comment by shatil** [comment]
YMMV, but I've been using Troposphere with Python 3 for a good long while now, and it's been working great.

**Comment by michael-k** [comment]
This can be closed. Troposphere 3.0 only supports Python 3.6+.
