### ISSUE TITLE
Cognito:RefreshTokenValidity internal failure in CF when float type is used

### ISSUE THREAD

**Issue by arnaudgay-cr** [cloudtools/troposphere#1485]
In last troposphere 2.5.1; the Cognito:RefreshTokenValidity changed from a positive-integer to a float. 
While in CF when a float is given the stack failed with the following error : 
`UPDATE_FAILED | AWS::Cognito::UserPoolClient | Client | Internal Failure`

AWS documentation describes this parameters as a "_number of days_".

**Comment by arnaudgay-cr** [comment]
Hi Mark, 
The above fixe has been successfully apply on my side.
BR

**Comment by markpeek** [comment]
Thanks. Fixed.

**Comment by arnaudgay-cr** [comment]
Hi,
When is the new tropo release expected with this fix?

I would like to evaluate the corrective plan on my side as many users are stuked with this. 
OR an heavy patching plan or temporized until new release.

Thanks in advance.

**Comment by mMeijden** [comment]
Should this be validated as a double at all? Since the AWS documentation refers to an integer.
`[2019-09-11 09:49:27] - cognito UserPoolClientApp AWS::Cognito::UserPoolClient UPDATE_FAILED Property validation failure: [Value of property {/RefreshTokenValidity} does not match type {Integer}]`

Shouldn't the positive_integer validator be used in this case?

**Comment by jk2l** [comment]
why is this updated in the first place. Now i am getting this error "Property validation failure: [Value of property {/RefreshTokenValidity} does not match type {Integer}]"

**Comment by jk2l** [comment]
I am using 2.5.3 btw

**Comment by jk2l** [comment]
actually my bad, my IDE configured wrong. was in 2.5.1, it seem fixed in 2.5.3, ignore my latest comment
