### ISSUE TITLE
Passing parameter into range()

### ISSUE THREAD

**Issue by reshrama** [cloudtools/troposphere#1504]
I am creating n number of EC2 instances for forming ECS Cluster using troposphere. I am passing Clustersize as parameter. 

```
ClusterSize = t.add_parameter (Parameter(
    "ClusterSize",
    Description= "Number of nodes needed for cluster. This needs to be input by user for nonASG",
    Type= "Number",
    Default= 1
```
In the tool I will be deploying my code, I have provision to input this value before deployment. So I thought of looping :
```
for i in range(ClusterSize):
    instance = t.add_resource(
        ec2.Instance(...)
   )
```
But I get the error : TypeError: range() integer end argument expected, got Parameter.
How do I do this?

**Comment by markpeek** [comment]
This is not possible since CloudFormation does not have ways to iterate within their templates. In other words, the range() iteration you're suggesting is being done locally as you generate the template. The ClusterSize parameter is input after you have submitted the template to CloudFormation and troposphere/python code is not executed there.My only suggestion would

**Comment by reshrama** [comment]
What about using AWS Macros and count? Can I dynamically pass the value to count and launch that many EC2 instances?  @markpeek

**Comment by markpeek** [comment]
Perhaps. I googled [this](https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/Count) which shows how to define a macro for count. I've never tried it but might give you a direction to try.
