### ISSUE TITLE
Add support for DataLocationResource & TableWithColumnsResource in AWS::LakeFormation::Permissions (2020, Jan 16 update)

### ISSUE THREAD

**Issue by axelpavageau** [cloudtools/troposphere#1564]
waiting for the doc to be updated

**Comment by PatMyron** [comment]
While these have made it into some CloudFormation Resource Specifications, they still haven't made it into the [`us-east-1` Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) yet:

https://github.com/ScriptAutomate/aws-cfn-resource-specs/blob/master/CHANGELOG.md

Both the documentation and Troposphere (and many similar tools like the [CDK](https://github.com/aws/aws-cdk)) use the [`us-east-1` Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) because it usually has every type:

![resources-per-region](https://user-images.githubusercontent.com/7014355/72749761-c2925500-3b6f-11ea-94e0-0c8e877eb24b.png)
