### ISSUE TITLE
Adopt a codestyle?

### ISSUE THREAD

**Issue by JohnPreston** [cloudtools/troposphere#1760]
Hi @markpeek 
Just wondering if it'd be worth as a validator to adopt something like [black ](https://pypi.org/project/black/) and use pre-commit to standardize code-style and pre-commit validations ? 
Just a thought ;)

**Comment by JohnPreston** [comment]
@markpeek @PatMyron thoughts?

**Comment by PatMyron** [comment]
[`flake8`](https://pypi.org/project/flake8/) is in place, which I prefer over [`black`](https://pypi.org/project/black/):
https://github.com/cloudtools/troposphere/blob/136c72ad9afd3ed6a07eb7d0571ae532264e7ebe/.travis.yml#L23

**Comment by ITProKyle** [comment]
Just putting in my two cents, usage of black is not a question of preference but time savings and efficiency.

For maintainers and contributes, not needing to even think of formatting code because it is done automatically can be invaluable in large scale open source projects. It also cuts down on the effort needed to review PRs as the formatting it enforces favors smaller diffs (not a _huge_ difference here but it is noticeable).

Pairing black with isort and running them via [pre-commit](https://pre-commit.com/) saves me and my team quite a bit of time during development and when reviewing PRs.

**Comment by JohnPreston** [comment]
Indeed I do too @ITProKyle hence the suggestion. Could be good timing too to adopt one with the 3.0 release.
@PatMyron correct me if I am wrong but flake8 is more focused on code quality with regards to PEP etc. than codestyle like black does?

**Comment by JohnPreston** [comment]
@markpeek I am guessing we can close this one too now we have 3.0 :rocket: 
So glad about isort + black
