### ISSUE TITLE
ManagedRuleGroupStatement missing ScopeDownStatement property

### ISSUE THREAD

**Issue by linasdsilva** [cloudtools/troposphere#2012]
wafv2.py ManagedRuleGroupStatement seems to be missing the ScopeDownStatement property, i.e. as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-managedrulegroupstatement.html definition.

**Comment by markpeek** [comment]
I explicitly removed it from v4.0.0-beta.0 as it was not present in v3.2.2. Looking at it closer, it will likely need to follow the One/Two/Three pattern present in this file to handle the cyclic use of Statement. In other words, this pattern which will break backward compatibility for any usage of the current ManagedRuleGroupStatement:
```
class ManagedRuleGroupStatementOne(AWSProperty):
    props: PropsDictType = {
        ...
        ScopeDownStatement: (StatementTwo, False),
        ...
    }
```
You are likely asking since you need it. Be curious what the community thinks about the backward compatibility issue. At least 4.0.0-beta is intended for some breaking changes.

Note: I've also thought about removing the One/Two/Three workaround and using a validation function to prevent the cyclic behavior.

**Comment by markpeek** [comment]
This was added in the above commit.
