### ISSUE TITLE
Plugin for visualops.io

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#207]
This is more of a feature request. It would be very helpful to be able to take exported JSON from http://www.visualops.io/ and generate a Troposphere script from it.

**Comment by phobologic** [comment]
Hey @BardiaAfshin - we're not familiar with that product, and it's unlikely that we'll get a lot of time to mess with it.  It's also a little outside the realm of what the core of troposphere is about.  That said, if you (or someone from visualops, or anyone even!) wanted to submit a pull request we would look at it.

Right now, since it's not really (at least as far as I'm aware) a very widely used community standard, I'm going to go ahead and close this issue (mostly to keep the issue list clean).

Thanks for the idea though!
