### ISSUE TITLE
route53 target Alias = yes

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#219]
I'm trying to create a Alias record in route53 with Cloudformation, and within troposphere I don't see how I can pass in AliasTarget = True in the examples. 

Here's what I have so far
```python
myDNSRecord_email = template.add_resource(RecordSetType(
    "myDNSRecordEmail",
    HostedZoneName=Join("", [Ref(hostedzone), "."]),
    Comment="DNS name for my instance.",
    Name=Join("", [
        "email", ".",
        Ref(hostedzone), "."
    ]),
    Type="A",
    TTL="900",
    ResourceRecords=[GetAtt("publicElasticLoadBalancer", "PublicIp")],
))
```

I need to know how to pass in a BaseRecordSet object with property AliasTarget=True.

**Comment by phobologic** [comment]
troposphere is a python implementation of the CloudFormation templating language.  If you see it in the docs in CloudFormation, you should be able to do the same in troposphere.  Notice how you use 'HostedZoneName'?  If you look at the CloudFormation documentation for RecordSet, you'll see that option is listed there, and they behave exactly the same:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html

You really shouldn't think of troposphere as a language of it's own.  It's just CloudFormation, but in python, rather than in JSON.  It has some extra helper features, but if you're looking for how to do something with a Resource Type or Property, your best bet is to consult the CloudFormation documentation for that ResourceType or Property.
