### ISSUE TITLE
Assign existing instance role?

### ISSUE THREAD

**Issue by khushil** [cloudtools/troposphere#377]
I'm having trouble seeing how to implement http://stackoverflow.com/questions/20329067/associating-an-existing-iam-role-with-awsec2instance-in-cloudformation/24148825#24148825 using troposphere?  How does one assign a pre-existing instance role in the UI to an instance upon creation without having to recreate using troposphere?

**Comment by markpeek** [comment]
If you have an existing role named "myexistingrolename" then you should be able to include in an Instance object creation something like this:
```
ec2_instance = template.add_resource(ec2.Instance(
    "Ec2Instance",
    ImageId="i-xxxxxx",
    InstanceType="t1.micro",
    KeyName=Ref(keyname_param),
    SecurityGroups=["default"],
    IamInstanceProfile="myexistingrolename",
))
```

**Comment by wt** [comment]
You have to have an instance profile. That is a different object as far as AWS is concerned.

The role you want associated with the instance needs to be added to the instance profile (aws iam add-role-to-instance-profile).

**Comment by BardiaAfshin** [comment]
from the source ec2.py 1.9.2

```python
class IamInstanceProfile(AWSProperty):
    props = {
        'Arn': (basestring, False),
    }


class LaunchSpecifications(AWSProperty):
    props = {
        'BlockDeviceMappings': ([BlockDeviceMapping], False),
        'EbsOptimized': (boolean, False),
        'IamInstanceProfile': (IamInstanceProfile, False),
```

@markpeek  do you need to pass to IamInstanceProfile a object? From the definition it doesn't look like it will take the string as you've specified but rather a IamInstanceProfile.

**Comment by phobologic** [comment]
That's only for LuanchSpecification, which is only used (as far as I can tell) with SpotFleet, so that doesn't apply here @BardiaAfshin. For the EC2 instance type, you'll use a string: https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L199

@wt is right that you'll need the name of an existing InstanceProfile with the appropriate Role attached to it to use for the argument of IamInstanceProfile.  If you don't already have one, you can create one with this: https://github.com/cloudtools/troposphere/blob/master/troposphere/iam.py#L64
