### ISSUE TITLE
Output duplicate key detected

### ISSUE THREAD

**Issue by Cinderhaze** [cloudtools/troposphere#390]
It is valid cloudformation syntax to have two output options with the same name, but two different condition flags set.

I am trying to create a template that creates a consistently named output with different values based on a conditional.

Using an example from http://www.unixdaemon.net/cloud/intro-to-cloudformations-conditionals/ as a basis
```
{
  "AWSTemplateFormatVersion": "2010-09-09",

  "Parameters" : {
    "DeploymentEnvironment" : {
      "Default": "dev",
      "Description" : "The environment this stack is being deployed to.",
      "Type" : "String",
      "AllowedValues" : [ "dev", "stage", "prod" ],
      "ConstraintDescription" : "Must be one of the following environments - dev | stage | prod"
    }
  },

  "Conditions": {
    "InProd": { "Fn::Equals" : [ { "Ref" : "DeploymentEnvironment" }, "prod" ] },

    "NotInProd": {
      "Fn::Or" : [
        { "Fn::Equals" : [ { "Ref" : "DeploymentEnvironment"}, "stage" ] },
        { "Fn::Equals" : [ { "Ref" : "DeploymentEnvironment"}, "dev" ] }
      ]
    }
  }
}
```

If I add a resource as shown in the link, and I add the following outputs to the file, it is a valid cloudformation template, and behaves as expected

```
"Outputs" : {
    "StageOut" : {
      "Condition": "InProd",
      "Description": "desc",
      "Value" : "Prod"
    },
   "StageOut" : {
      "Condition": "NotInProd",
      "Description": "desc",
      "Value" : "Not Prod"
    },
}

```

However, if I create the same configuration in troposphere...
```
StageOut1 = t.add_output(Output(
  "StageOut",
  Condition="InProd",
  Description="desc",
  value="Prod",
))
StageOut2 = t.add_output(Output(
  "StageOut",
  Condition="NotInProd",
  Description="desc",
  value="Not Prod",
))
```

...I get the following error
`ValueError: duplicate key "StageOut" detected`

The key for a (output) resource should probably be a combination of it's name and it's conditional (if it has one), not just the name of the resource.

**Comment by phobologic** [comment]
While it's technically allowed by Cloudformation, I don't think it provides the behavior you're looking for.  Take this CFN template:

https://gist.github.com/phobologic/486929b206180b164358

If you upload that, and provide the `prod` value to the Parameter, you'll see that no Output shows up at all.  If you provide `dev` or `stage` the not in prod output gets created.  The only reason I can think that is, is because the `Outputs` section is a json 'object' (in python, a `dict`), so it's semi-randomly (not sure how it picks, it probably isn't order, but who knows) one of the values for the output.  In this case it's always picking the NotInProd one, which means that when you provide values that match it, the Output exists.  When you provide values that don't (ie `prod`) the output doesn't exist at all.

So, while technically this should be allowed, I think Troposphere is actually doing the right thing by stopping people from doing something that isn't what they believe.  Let me know, if you test with that Cloudformation Template, if you see different results.

**Comment by phobologic** [comment]
Ah, and a quick google search answered my question above:

http://stackoverflow.com/questions/5306741/do-json-keys-need-to-be-unique

```
There is no "error" if you use more than one key with the same name, but in JSON, the last key with the same name is the one that is going to be used.
```

**Comment by phobologic** [comment]
BTW, to get the behavior you seem to want (An output whose name doesn't change, but it's value does based on a condition) use the `If` helper function:

```
t.add_output(
    Output(
        "StageOut",
        Description="desc",
        Value=If("InProd", "Prod", "Not Prod")
    )
)
```

**Comment by Cinderhaze** [comment]
I was thinking about how to do it after posting this issue, and I thought of the latter condition you had mentioned.  

The way I was originally going to use this was to have a template which I could either specify for it to use RDS, or to give it a known database URI.  I would have my app reading from the output of the template, but it would allow me to use a preexisting RDS for my test environment (where I could just drop all tables and use that instance), but in my prod environment I could just let the cloudformation template manage the RDS instance.

I also had another use case where I could pass in a private IP to use with an {Instance,ENI}, and if I didn't pass in a value, it would auto-assign one, and I would return the private IP off of the {Instance,ENI}.

In both of those cases, I would be able to use the above 'If' construct to choose my output.

Thanks for following up with my issue!

**Comment by phobologic** [comment]
Cool - yeah, in the end, using a duplicate key is something you definitely don't want to do :)  I like to think of this as a feature of troposphere, rather than a bug :)  Good luck with your templating!
