### ISSUE TITLE
Can you release 1.9.5 please?

### ISSUE THREAD

**Issue by rtkmhart** [cloudtools/troposphere#775]
I really need this commit https://github.com/cloudtools/troposphere/commit/94a55dfc68fcd2352f867b01fc703a202c87f453 for what I'm working on which is post 1.9.4. Any chance you could release 1.9.5?

Greatly appreciate what you're doing here!

**Comment by markpeek** [comment]
@rtkmhart I've been trying to resolve upstream issues with the cfn_flip project which has caused build breakage. I submitted a fix over the weekend but it hasn't been picked up yet. I'm at a point where I may just revert the YAML changes (removing the cfn_flip dependency) in order to put out a release. Sorry for the delay.

**Comment by kaylashapiro** [comment]
This would help us too as we need the Dynamo TTL Spec and Tags.

**Comment by markpeek** [comment]
@rtkmhart @kaylashapiro Thank you for your patience. I reverted a couple of troublesome commits and just now released 1.9.5.

**Comment by rtkmhart** [comment]
Thanks @markpeek greatly appreciate your fast response!

I don't think this saga is over yet unfortunately, the CloudFormation docs don't seem to match the API. If you set a RoleArn on an Event Target, CloudFormation barfs on it. This support case suggests the docs aren't accurate: https://forums.aws.amazon.com/thread.jspa?messageID=788838&#788838

I'm going to open a support case and see what's up, will post what I can here.
